name: refs
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.11.14=py312h178313f_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - aom=3.9.1=hac33072_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - asciitree=0.3.3=py_2
  - attr=2.5.1=h166bdaf_1
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-auth=0.8.6=hd08a7f5_4
  - aws-c-cal=0.8.7=h043a21b_0
  - aws-c-common=0.12.0=hb9d3cd8_0
  - aws-c-compression=0.3.1=h3870646_2
  - aws-c-event-stream=0.5.4=h04a3f94_2
  - aws-c-http=0.9.4=hb9b18c6_4
  - aws-c-io=0.17.0=h3dad3f2_6
  - aws-c-mqtt=0.12.2=h108da3e_2
  - aws-c-s3=0.7.13=h822ba82_2
  - aws-c-sdkutils=0.2.3=h3870646_2
  - aws-checksums=0.2.3=h3870646_2
  - aws-crt-cpp=0.31.0=h55f77e1_4
  - aws-sdk-cpp=1.11.510=h37a5c72_3
  - azure-core-cpp=1.14.0=h5cfcd09_0
  - azure-identity-cpp=1.10.0=h113e628_0
  - azure-storage-blobs-cpp=12.13.0=h3cf044e_1
  - azure-storage-common-cpp=12.8.0=h736e048_1
  - azure-storage-files-datalake-cpp=12.12.0=ha633028_1
  - blosc=1.21.6=he440d0b_1
  - bokeh=3.7.0=pyhd8ed1ab_0
  - boltons=24.0.0=pyhd8ed1ab_1
  - bottleneck=1.4.2=py312hc0a28a1_0
  - branca=0.8.1=pyhd8ed1ab_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py312h2ec8cdc_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.1.31=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cartopy=0.24.0=py312hf9745cd_0
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cf_xarray=0.10.4=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - cftime=1.6.4=py312hc0a28a1_1
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - clisops=0.16.1=pyhd8ed1ab_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - contourpy=1.3.1=py312h68727a3_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cytoolz=1.0.1=py312h66e93f0_0
  - dask=2024.11.2=pyhff2d567_1
  - dask-core=2024.11.2=pyhff2d567_1
  - dask-expr=1.1.19=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - distributed=2024.11.2=pyhff2d567_1
  - entrypoints=0.4=pyhd8ed1ab_1
  - esmf=8.8.0=mpi_mpich_h7cf99a1_100
  - esmpy=8.8.0=pyhecae5ae_1
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - fasteners=0.19=pyhd8ed1ab_1
  - fastprogress=1.0.3=pyhd8ed1ab_1
  - filelock=3.18.0=pyhd8ed1ab_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - flox=0.10.1=pyhd8ed1ab_0
  - folium=0.19.5=pyhd8ed1ab_0
  - fonttools=4.56.0=py312h178313f_0
  - freetype=2.13.3=h48d6fc4_0
  - freexl=2.0.0=h9dce30a_2
  - frozenlist=1.5.0=py312h178313f_1
  - fsspec=2025.3.1=pyhd8ed1ab_0
  - geopandas=1.0.1=pyhd8ed1ab_3
  - geopandas-base=1.0.1=pyha770c72_3
  - geos=3.13.1=h97f6797_0
  - geotiff=1.7.4=h239500f_2
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - gtest=1.16.0=h84d6215_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5netcdf=1.6.1=pyhd8ed1ab_0
  - h5py=3.13.0=nompi_py312hedeef09_100
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=mpi_mpich_h7f58efa_9
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - intake=0.7.0=pyhd8ed1ab_0
  - intake-esm=2024.2.6=pyhd8ed1ab_2
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - json-c=0.18=h6688a6e_0
  - jsonpickle=4.0.0=pyh29332c3_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.8=py312h84d6215_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h27087fc_0
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libaec=1.1.3=h59595ed_0
  - libarchive=3.7.7=h4585015_3
  - libarrow=19.0.1=h120c447_5_cpu
  - libarrow-acero=19.0.1=hcb10f89_5_cpu
  - libarrow-dataset=19.0.1=hcb10f89_5_cpu
  - libarrow-substrait=19.0.1=h1bed206_5_cpu
  - libavif16=1.2.1=hbb36593_2
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.12.1=h332b0f4_0
  - libde265=1.0.15=h00ab1b0_0
  - libdeflate=1.23=h4ddbbb0_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.0=h5888daf_0
  - libfabric=2.1.0=ha770c72_0
  - libfabric1=2.1.0=h14e6f36_0
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgdal-core=3.10.2=hae73b24_5
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - libgoogle-cloud=2.36.0=hc4361e1_1
  - libgoogle-cloud-storage=2.36.0=h0121fbd_1
  - libgpg-error=1.51=hbd13f7d_1
  - libgrpc=1.71.0=he753a82_0
  - libheif=1.19.7=gpl_hc18d805_100
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.0.0=hd590300_1
  - libkml=1.3.0=hf539b9f_1021
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblzma=5.6.4=hb9d3cd8_0
  - libnetcdf=4.9.2=mpi_mpich_h761946e_14
  - libnghttp2=1.64.0=h161d5f1_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libopentelemetry-cpp=1.19.0=hd1b1c89_0
  - libopentelemetry-cpp-headers=1.19.0=ha770c72_0
  - libparquet=19.0.1=h081d1f1_5_cpu
  - libpnetcdf=1.13.0=mpi_mpich_hdce4f7b_101
  - libpng=1.6.47=h943b412_0
  - libprotobuf=5.29.3=h501fc15_0
  - libre2-11=2024.07.02=hba17884_3
  - librttopo=1.1.0=hd718a1a_18
  - libspatialite=5.1.0=he17ca71_14
  - libsqlite=3.49.1=hee588c1_2
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libsystemd0=257.4=h4e0b6ca_1
  - libthrift=0.21.0=h0e7cc3e_0
  - libtiff=4.7.0=hd9ff511_3
  - libudev1=257.4=hbe16f8c_1
  - libutf8proc=2.10.0=h4c51ac1_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.7=h8d12d68_0
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.44.0=py312h374181b_1
  - locket=1.0.0=pyhd8ed1ab_0
  - loguru=0.7.2=py312h7900ff3_2
  - lz4=4.3.3=py312hf0f0c11_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - mapclassify=2.8.1=pyhd8ed1ab_1
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py312h178313f_1
  - matplotlib-base=3.10.1=py312hd3ec401_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - minizip=4.0.7=h05a5f5f_3
  - mpi=1.0.1=mpich
  - mpich=4.3.0=h1a8bee6_100
  - msgpack-python=1.1.0=py312h68727a3_0
  - multidict=6.2.0=py312h178313f_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=pyha770c72_1
  - narwhals=1.32.0=pyhd8ed1ab_0
  - nc-time-axis=1.4.1=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - netcdf-fortran=4.6.1=mpi_mpich_h2e543cf_8
  - netcdf4=1.7.2=nompi_py312h21d6d8e_101
  - networkx=3.4.2=pyh267e887_2
  - nlohmann_json=3.11.3=he02047a_1
  - numba=0.61.0=py312h2e6246c_1
  - numcodecs=0.15.1=py312hf9745cd_0
  - numpy=1.26.4=py312heda63a1_0
  - numpy_groupies=0.11.2=pyhd8ed1ab_1
  - openjpeg=2.5.3=h5fbd93e_0
  - openpyxl=3.1.5=py312h710cb58_1
  - openssl=3.4.1=h7b32b05_0
  - orc=2.1.1=h17f744e_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py312hf9745cd_1
  - parallelio=2.6.3=mpi_mpich_h43d51f9_100
  - parse=1.20.2=pyhd8ed1ab_1
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=hba22ea6_2
  - pillow=11.1.0=py312h80c1187_0
  - pint=0.24.4=pyhd8ed1ab_1
  - pip=25.0.1=pyh8b19718_0
  - platformdirs=4.3.7=pyh29332c3_0
  - pooch=1.8.2=pyhd8ed1ab_1
  - proj=9.6.0=h0054346_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - propcache=0.2.1=py312h178313f_1
  - psutil=7.0.0=py312h66e93f0_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyarrow=19.0.1=py312h7900ff3_0
  - pyarrow-core=19.0.1=py312h01725c0_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.1=pyh3cfb1c2_0
  - pydantic-core=2.33.0=py312h3b7be25_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyogrio=0.10.0=py312h02b19dd_1
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyproj=3.7.1=py312h03c6e1f_1
  - pyshp=2.3.1=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.9=h9e4cc4f_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h178313f_2
  - qhull=2020.2=h434a139_5
  - rav1e=0.6.6=he8a937b_2
  - rdma-core=56.0=h5888daf_0
  - re2=2024.07.02=h9925aae_3
  - readline=8.2=h8c095d6_2
  - rechunker=0.5.3=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rich=14.0.0=pyh29332c3_0
  - roocs-grids=0.1.2=pyhd8ed1ab_1
  - s2n=1.5.14=h6c98b2b_0
  - scikit-learn=1.6.1=py312h7a48858_0
  - scipy=1.15.2=py312ha707e6e_0
  - setuptools=75.8.2=pyhff2d567_0
  - shapely=2.0.7=py312h21f5128_1
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h8bd8927_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - sparse=0.15.5=pyh72ffeb9_0
  - sqlite=3.49.1=h9eae976_2
  - statsmodels=0.14.4=py312hc0a28a1_0
  - svt-av1=3.0.2=h5888daf_0
  - tblib=3.0.0=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h4845f30_101
  - tmux=3.5=h4463017_0
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.4.2=py312h66e93f0_0
  - typer=0.15.2=pyhff008b6_0
  - typer-slim=0.15.2=pyh29332c3_0
  - typer-slim-standard=0.15.2=h801b22e_0
  - typing-extensions=4.13.0=h9fa5a19_1
  - typing-inspection=0.4.0=pyhd8ed1ab_0
  - typing_extensions=4.13.0=pyh29332c3_1
  - tzdata=2025b=h78e105d_0
  - ucx=1.18.0=hfd9a62f_2
  - unicodedata2=16.0.0=py312h66e93f0_0
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.3.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.2=py312h66e93f0_0
  - x265=3.5=h924138e_3
  - xarray=2025.1.2=pyhd8ed1ab_0
  - xclim=0.55.1=pyhd8ed1ab_0
  - xerces-c=3.2.5=h988505b_2
  - xesmf=0.8.7=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xscen=0.12.0=pyhd8ed1ab_1
  - xsdba=0.3.2=pyhd8ed1ab_0
  - xyzservices=2025.1.0=pyhd8ed1ab_0
  - yamale=5.3.0=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.18.3=py312h178313f_1
  - zarr=2.18.4=pyhd8ed1ab_0
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py312h66e93f0_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - cairocffi==1.7.1
      - cairosvg==2.7.1
      - cssselect2==0.8.0
      - defusedxml==0.7.1
      - figanos==0.4.0
      - imageio==2.37.0
      - lazy-loader==0.4
      - scikit-image==0.25.2
      - seaborn==0.13.2
      - tifffile==2025.3.30
      - tinycss2==1.4.0
      - webencodings==0.5.1
prefix: /exec/jlavoie/.conda/refs
