name: obsflow
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.14
  - aiosignal=1.3.2
  - annotated-types=0.7.0
  - aom=3.9.1
  - appdirs=1.4.4
  - asciitree=0.3.3
  - asttokens=3.0.0
  - attr=2.5.1
  - attrs=25.3.0
  - aws-c-auth=0.8.6
  - aws-c-cal=0.8.7
  - aws-c-common=0.12.0
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.9.4
  - aws-c-io=0.17.0
  - aws-c-mqtt=0.12.2
  - aws-c-s3=0.7.13
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.3
  - aws-crt-cpp=0.31.0
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - blosc=1.21.6
  - bokeh=3.7.0
  - boltons=24.0.0
  - bottleneck=1.4.2
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.4
  - c-blosc2=2.15.2
  - ca-certificates=2025.7.14
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - cairocffi=1.7.1
  - cairosvg=2.7.1
  - cartopy=0.24.0
  - cattrs=25.1.1
  - certifi=2025.7.14
  - cf_xarray=0.10.4
  - cffi=1.17.1
  - cftime=1.6.4
  - charls=2.4.2
  - charset-normalizer=3.4.1
  - click=8.1.8
  - clisops=0.16.1
  - cloudpickle=3.1.1
  - comm=0.2.3
  - contourpy=1.3.1
  - cpython=3.12.11
  - cssselect2=0.8.0
  - cycler=0.12.1
  - cytoolz=1.0.1
  - dask=2025.7.0
  - dask-core=2025.7.0
  - dask-expr=2.0.0
  - dav1d=1.2.1
  - debugpy=1.8.15
  - decorator=5.2.1
  - defusedxml=0.7.1
  - deprecated=1.2.18
  - distributed=2025.7.0
  - docopt-ng=0.9.0
  - entrypoints=0.4
  - esmf=8.8.0
  - esmpy=8.8.0
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - fasteners=0.19
  - fastprogress=1.0.3
  - figanos=0.4.0
  - filelock=3.18.0
  - flexcache=0.3
  - flexparser=0.4
  - flox=0.10.1
  - folium=0.19.5
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.56.0
  - freetype=2.13.3
  - freexl=2.0.0
  - frozenlist=1.5.0
  - fsspec=2025.3.1
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geos=3.13.1
  - geotiff=1.7.4
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - gtest=1.16.0
  - h2=4.2.0
  - h5netcdf=1.6.1
  - h5py=3.13.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imagecodecs=2024.12.30
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - intake=2.0.8
  - intake-esm=2025.2.3
  - ipykernel=6.30.0
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - json-c=0.18
  - jsonpickle=4.0.0
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lazy-loader=0.4
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - legacy-cgi=2.6.3
  - lerc=4.0.0
  - libabseil=20250127.1
  - libaec=1.1.3
  - libarchive=3.7.7
  - libarrow=19.0.1
  - libarrow-acero=19.0.1
  - libarrow-dataset=19.0.1
  - libarrow-substrait=19.0.1
  - libavif16=1.2.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.75
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.12.1
  - libde265=1.0.15
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libfabric=2.1.0
  - libfabric1=2.1.0
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.0
  - libgdal-core=3.10.2
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.84.1
  - libgomp=15.1.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgpg-error=1.51
  - libgrpc=1.71.0
  - libheif=1.19.7
  - libhwloc=2.11.2
  - libhwy=1.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libopentelemetry-cpp=1.19.0
  - libopentelemetry-cpp-headers=1.19.0
  - libparquet=19.0.1
  - libpnetcdf=1.13.0
  - libpng=1.6.47
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.4
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libudev1=257.4
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.7
  - libxslt=1.1.39
  - libzip=1.11.2
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvmlite=0.44.0
  - locket=1.0.0
  - loguru=0.7.2
  - lxml=5.4.0
  - lz4=4.3.3
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.8.1
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.1
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - minizip=4.0.7
  - mpi=1.0.1
  - mpich=4.3.0
  - msgpack-python=1.1.0
  - multidict=6.2.0
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - narwhals=1.32.0
  - nc-time-axis=1.4.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf-fortran=4.6.1
  - netcdf4=1.7.2
  - networkx=3.4.2
  - nlohmann_json=3.11.3
  - numba=0.61.0
  - numcodecs=0.15.1
  - numpy=1.26.4
  - numpy_groupies=0.11.2
  - openjpeg=2.5.3
  - openpyxl=3.1.5
  - openssl=3.5.1
  - orc=2.1.1
  - packaging=25.0
  - pandas=2.2.3
  - parallelio=2.6.3
  - parse=1.20.2
  - parso=0.8.4
  - partd=1.4.2
  - patsy=1.0.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pint=0.24.4
  - pip=25.1.1
  - pixman=0.46.2
  - platformdirs=4.3.8
  - polars=1.31.0
  - polars-default=1.31.0
  - pooch=1.8.2
  - proj=9.6.0
  - prometheus-cpp=1.3.0
  - prompt-toolkit=3.0.51
  - propcache=0.2.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=19.0.1
  - pyarrow-core=19.0.1
  - pycparser=2.22
  - pydantic=2.11.1
  - pydantic-core=2.33.0
  - pydap=3.5.4
  - pygments=2.19.2
  - pyogrio=0.10.0
  - pyparsing=3.2.3
  - pyproj=3.7.1
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.12.10
  - python-dateutil=2.9.0.post0
  - python-gil=3.12.11
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2024.1
  - pywavelets=1.8.0
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - qhull=2020.2
  - rav1e=0.6.6
  - rdma-core=56.0
  - re2=2024.07.02
  - readline=8.2
  - rechunker=0.5.3
  - requests=2.32.3
  - requests-cache=1.2.1
  - rich=14.0.0
  - roocs-grids=0.1.2
  - s2n=1.5.14
  - scikit-image=0.25.2
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - shapely=2.0.7
  - shellingham=1.5.4
  - six=1.17.0
  - snappy=1.2.1
  - sortedcontainers=2.4.0
  - soupsieve=2.7
  - sparse=0.15.5
  - sqlite=3.49.1
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - svt-av1=3.0.2
  - tblib=3.0.0
  - threadpoolctl=3.6.0
  - tifffile=2025.3.30
  - tinycss2=1.4.0
  - tk=8.6.13
  - tmux=3.5
  - toolz=1.0.0
  - tornado=6.5.1
  - traitlets=5.14.3
  - typer=0.15.2
  - typer-slim=0.15.2
  - typer-slim-standard=0.15.2
  - typing-extensions=4.13.0
  - typing-inspection=0.4.0
  - typing_extensions=4.13.0
  - tzdata=2025b
  - ucx=1.18.0
  - ujson=5.10.0
  - unicodedata2=16.0.0
  - uriparser=0.9.8
  - url-normalize=2.2.1
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - webob=1.8.9
  - wheel=0.45.1
  - wrapt=1.17.2
  - x265=3.5
  - xarray=2025.6.1
  - xclim=0.57.0
  - xerces-c=3.2.5
  - xesmf=0.8.10
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xscen=0.12.3
  - xsdba=0.5.0
  - xyzservices=2025.1.0
  - yamale=5.3.0
  - yaml=0.2.5
  - yarl=1.18.3
  - zarr=2.18.4
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.4
  - zstandard=0.23.0
  - zstd=1.5.7
